# Site settings
title: PennApps Mentoring
description: ""
baseurl: ""
url: "http://pennapps.mentoring.com"

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
